"use client";
import { useState } from "react";
import { useApiClient } from "@kannan19302/framework";
import { Button } from "@kannan19302/ui";
import { Eye, X } from "lucide-react";
import { useAsyncData } from "@/platform/data/useAsyncData";
import { createProjectPreview, listProjectPreviews, revokeProjectPreview } from "@/platform/data/projects";
import { relativeTime } from "./relative-time";
import styles from "./project-overview.module.css";
export function ProjectPreviewPanel({ projectId }: { projectId: string }) {
  const client = useApiClient(); const previews = useAsyncData(() => listProjectPreviews(client, projectId), [projectId]); const [role, setRole] = useState(""); const [locale, setLocale] = useState("en"); const [device, setDevice] = useState<"desktop" | "tablet" | "mobile">("desktop"); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [created, setCreated] = useState<{ token: string; status: string } | null>(null);
  const create = async () => { setBusy(true); setError(null); try { const preview = await createProjectPreview(client, projectId, { role: role || undefined, locale, device }); setCreated(preview.token ? { token: preview.token, status: preview.status ?? "PENDING" } : null); await previews.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not create preview"); } finally { setBusy(false); } };
  const revoke = async (id: string) => { setBusy(true); try { await revokeProjectPreview(client, projectId, id); await previews.refetch(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not revoke preview"); } finally { setBusy(false); } };
  return <section className={styles.section}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: "var(--space-4)" }}><div><h2 className={styles.section_title}>Preview</h2><p className={styles.section_hint}>Run the current composition in an isolated, short-lived session—not against a production release.</p></div><Eye size={17} /></div><div className={styles.changes} style={{ padding: "var(--space-3)", marginTop: "var(--space-3)" }}><input aria-label="Preview role" placeholder="Role (optional)" value={role} onChange={(event) => setRole(event.target.value)} /><input aria-label="Preview locale" value={locale} onChange={(event) => setLocale(event.target.value)} /><select aria-label="Preview device" value={device} onChange={(event) => setDevice(event.target.value as typeof device)}><option value="desktop">Desktop</option><option value="tablet">Tablet</option><option value="mobile">Mobile</option></select><Button variant="secondary" size="sm" disabled={busy} onClick={create}>{busy ? "Starting…" : "Start preview"}</Button><Button variant="ghost" size="sm" disabled={busy || previews.loading} onClick={previews.refetch}>Refresh status</Button></div>{created && <div className={styles.empty}>Preview is <strong>{created.status.toLowerCase()}</strong> while its isolated plan is prepared. Keep this one-time opaque token private: <code>{created.token}</code></div>}{error && <div className={styles.empty}>{error}</div>}{(previews.data ?? []).map((preview) => <div key={preview.id} className={styles.changes}><div className={styles.change}><div className={styles.change_main}><span className={styles.change_name}>{preview.context.device ?? "desktop"} · {preview.context.locale ?? "en"}</span><span className={styles.change_when}>{preview.sourceFingerprint.slice(0, 12)}… · {preview.status ?? "ACTIVE"}</span></div><span className={styles.change_when}>Expires {relativeTime(preview.expiresAt)}</span><Button variant="ghost" size="sm" disabled={busy || preview.status === "REVOKED"} leftIcon={<X size={13} />} onClick={() => revoke(preview.id)}>Revoke</Button></div></div>)}</section>;
}
