"use client";
import { ChangeEvent, useState } from "react";
import { useApiClient } from "@kannan19302/framework";
import { Button } from "@kannan19302/ui";
import { Code2, Download } from "lucide-react";
import { applyProjectSourceImport, exportProjectSource, planProjectSourceImport, type ProjectSourceExport, type ProjectSourceImportPlan, type ProjectSourceImportResolution } from "@/platform/data/projects";
import styles from "./project-overview.module.css";

export function ProjectSourcePanel({ projectId }: { projectId: string }) {
  type ResolutionDraft = { action?: "KEEP_CURRENT" | "APPLY_INCOMING"; approvedBreaking?: boolean; resourceMappings?: string; capabilityGrants?: string };
  const client = useApiClient(); const [bundle, setBundle] = useState<ProjectSourceExport | null>(null); const [error, setError] = useState<string | null>(null); const [importBundle, setImportBundle] = useState<unknown>(null); const [plan, setPlan] = useState<ProjectSourceImportPlan | null>(null); const [resolutions, setResolutions] = useState<Record<string, ResolutionDraft>>({}); const [busy, setBusy] = useState(false);
  const download = async () => { setError(null); try { const result = await exportProjectSource(client, projectId); setBundle(result); const url = URL.createObjectURL(new Blob([JSON.stringify(result, null, 2)], { type: "application/json" })); const link = document.createElement("a"); link.href = url; link.download = `${projectId}.unierp.json`; link.click(); URL.revokeObjectURL(url); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not export source"); } };
  const choose = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setError(null); setPlan(null); setResolutions({}); try { setImportBundle(JSON.parse(await file.text())); } catch { setImportBundle(null); setError("The selected file is not valid JSON."); } };
  const inspect = async () => { if (!importBundle) return; setBusy(true); setError(null); setResolutions({}); try { setPlan(await planProjectSourceImport(client, projectId, importBundle)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not inspect source import"); } finally { setBusy(false); } };
  const apply = async () => { if (!importBundle || !plan) return; setBusy(true); setError(null); try { const governed = Object.fromEntries(Object.entries(resolutions).map(([id, draft]) => { if (draft.action !== "APPLY_INCOMING") return [id, "KEEP_CURRENT"]; let resourceMappings: Record<string, unknown> | undefined; let capabilityGrants: unknown[] | undefined; if (draft.resourceMappings?.trim()) { const parsed = JSON.parse(draft.resourceMappings); if (!parsed || Array.isArray(parsed) || typeof parsed !== "object") throw new Error("Resource mappings must be a JSON object."); resourceMappings = parsed; } if (draft.capabilityGrants?.trim()) { const parsed = JSON.parse(draft.capabilityGrants); if (!Array.isArray(parsed)) throw new Error("Capability grants must be a JSON array."); capabilityGrants = parsed; } return [id, { action: "APPLY_INCOMING", approvedBreaking: Boolean(draft.approvedBreaking), resourceMappings, capabilityGrants } satisfies ProjectSourceImportResolution]; })); await applyProjectSourceImport(client, projectId, importBundle, governed); setPlan(null); setImportBundle(null); setResolutions({}); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not apply source import"); } finally { setBusy(false); } };
  const importBlocked = Boolean(plan?.conflicts.some((conflict) => !resolutions[conflict.id]?.action));
  const updateResolution = (id: string, patch: Partial<ResolutionDraft>) => setResolutions((current) => ({ ...current, [id]: { ...current[id], ...patch } }));
  const applyLabel = plan?.changes.removed.length ? "Apply artifact removals" : plan?.changes.added.length ? "Apply new artifacts" : "Apply revision updates";
  return <section className={styles.section}>
    <div style={{ display: "flex", justifyContent: "space-between", alignItems: "start", gap: "var(--space-4)" }}><div><h2 className={styles.section_title}>Source export</h2><p className={styles.section_hint}>Download canonical IR for CLI, Git, and IDE workflows. Revisions remain governed by the same project policies.</p></div><Button variant="secondary" size="sm" leftIcon={<Download size={14} />} onClick={download}>Export source</Button></div>
    {error && <div className={styles.empty}>{error}</div>}
    {bundle && <div className={styles.changes}><div className={styles.change}><div className={styles.change_main}><Code2 size={15} /><span className={styles.change_name}>{bundle.artifacts.length} artifact sources</span><span className={styles.change_when}>{bundle.packages.length} locked packages</span></div><span className={styles.origin}>{bundle.bundleHash.slice(0, 12)}…</span></div></div>}
    <div className={styles.changes} style={{ padding: "var(--space-3)", marginTop: "var(--space-3)" }}><span className={styles.section_hint}>Import canonical source</span><input type="file" accept="application/json,.json" onChange={choose} /><Button variant="secondary" size="sm" disabled={!importBundle || busy} onClick={inspect}>{busy ? "Inspecting…" : "Inspect changes"}</Button>{plan && <><span className={styles.change_when}>{plan.changes.changed.length} updates · {plan.changes.added.length} adds · {plan.changes.removed.length} removals · {plan.conflicts.length} dependency conflicts</span>{plan.conflicts.map((conflict) => { const draft = resolutions[conflict.id] ?? {}; return <div key={conflict.id} className={styles.change} style={{ alignItems: "start" }}><div className={styles.change_main}><span className={styles.change_name}>{conflict.domain.replaceAll("_", " ")} · {conflict.key}</span><span className={styles.change_when}>{conflict.change}</span></div><div style={{ display: "grid", gap: "var(--space-2)", minWidth: "19rem" }}><select aria-label={`Resolve ${conflict.id}`} value={draft.action ?? ""} onChange={(event) => updateResolution(conflict.id, { action: event.target.value as ResolutionDraft["action"] })}><option value="">Choose resolution</option><option value="KEEP_CURRENT">Keep current project value</option><option value="APPLY_INCOMING" disabled={!conflict.applyIncomingReady}>Apply incoming signed version</option></select>{draft.action === "APPLY_INCOMING" && <><label className={styles.change_when}><input type="checkbox" checked={Boolean(draft.approvedBreaking)} onChange={(event) => updateResolution(conflict.id, { approvedBreaking: event.target.checked })} /> Approve breaking/changed exports</label><textarea aria-label={`Resource mappings for ${conflict.key}`} placeholder='Resource mappings JSON, e.g. {"crm":"artifact-id"}' value={draft.resourceMappings ?? ""} onChange={(event) => updateResolution(conflict.id, { resourceMappings: event.target.value })} /><textarea aria-label={`Capability grants for ${conflict.key}`} placeholder='Capability grants JSON, e.g. ["data.write"]' value={draft.capabilityGrants ?? ""} onChange={(event) => updateResolution(conflict.id, { capabilityGrants: event.target.value })} /></>}</div></div>; })}<Button variant="primary" size="sm" disabled={busy || importBlocked || (plan.changes.added.length + plan.changes.changed.length + plan.changes.removed.length + plan.conflicts.length === 0)} onClick={apply}>{busy ? "Applying…" : applyLabel}</Button>{plan.changes.removed.length > 0 && <span className={styles.change_when}>Removals are soft-deleted only after dependency and package-retention checks.</span>}{plan.conflicts.length > 0 && <span className={styles.change_when}>Incoming locks and binding requirements are never guessed. Signed package changes can apply atomically after mappings, grants, compatibility, impact and orphan checks; other conflict kinds remain fail-closed.</span>}</>}</div>
  </section>;
}
