/**
 * UniERP Developer Platform v1 - Canonical 108 Screen Registry
 * Generated from SCREEN_MANIFEST.json
 */

export interface ScreenDescriptor {
  id: number;
  screenId: string;
  originId: number;
  title: string;
  group: string;
  file: string;
  kind: string;
  gap: string | null;
  canonicalRoute: string;
  imagePath: string;
}

export const JOURNEY_GROUPS = [
  "01 Start and navigate",
  "02 Compose and reuse",
  "03 Build websites",
  "04 Build applications",
  "05 Integrate and extend",
  "06 Validate and deliver",
  "07 Secure and operate",
] as const;

export type JourneyGroup = (typeof JOURNEY_GROUPS)[number];

export const ALL_SCREENS: ScreenDescriptor[] = [
  {
    "id": 1,
    "screenId": "DP-001",
    "originId": 73,
    "title": "Sign-in handoff and callback recovery",
    "group": "01 Start and navigate",
    "file": "001_auth_states.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/auth/states",
    "imagePath": "/designs/001_auth_states.png"
  },
  {
    "id": 2,
    "screenId": "DP-002",
    "originId": 77,
    "title": "Developer getting started",
    "group": "01 Start and navigate",
    "file": "002_developer_getting_started_refined.png",
    "kind": "Enterprise addition",
    "gap": "Guided project readiness",
    "canonicalRoute": "/getting-started",
    "imagePath": "/designs/002_developer_getting_started_refined.png"
  },
  {
    "id": 3,
    "screenId": "DP-003",
    "originId": 1,
    "title": "Projects workspace",
    "group": "01 Start and navigate",
    "file": "003_projects.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects",
    "imagePath": "/designs/003_projects.png"
  },
  {
    "id": 4,
    "screenId": "DP-004",
    "originId": 2,
    "title": "Create project",
    "group": "01 Start and navigate",
    "file": "004_create_project.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/new",
    "imagePath": "/designs/004_create_project.png"
  },
  {
    "id": 5,
    "screenId": "DP-005",
    "originId": 3,
    "title": "Project overview",
    "group": "01 Start and navigate",
    "file": "005_project_overview.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/supplier-experience",
    "imagePath": "/designs/005_project_overview.png"
  },
  {
    "id": 6,
    "screenId": "DP-006",
    "originId": 78,
    "title": "Project work items",
    "group": "01 Start and navigate",
    "file": "006_work_items.png",
    "kind": "Enterprise addition",
    "gap": "Work item planning",
    "canonicalRoute": "/projects/supplier-experience/work-items",
    "imagePath": "/designs/006_work_items.png"
  },
  {
    "id": 7,
    "screenId": "DP-007",
    "originId": 17,
    "title": "Applications catalog",
    "group": "01 Start and navigate",
    "file": "007_applications.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/apps",
    "imagePath": "/designs/007_applications.png"
  },
  {
    "id": 8,
    "screenId": "DP-008",
    "originId": 18,
    "title": "Websites catalog",
    "group": "01 Start and navigate",
    "file": "008_websites.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/sites",
    "imagePath": "/designs/008_websites.png"
  },
  {
    "id": 9,
    "screenId": "DP-009",
    "originId": 19,
    "title": "Create application",
    "group": "01 Start and navigate",
    "file": "009_new_application.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/apps/new",
    "imagePath": "/designs/009_new_application.png"
  },
  {
    "id": 10,
    "screenId": "DP-010",
    "originId": 20,
    "title": "Create website and templates",
    "group": "01 Start and navigate",
    "file": "010_new_website.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/sites/new",
    "imagePath": "/designs/010_new_website.png"
  },
  {
    "id": 11,
    "screenId": "DP-011",
    "originId": 6,
    "title": "Standalone builders",
    "group": "01 Start and navigate",
    "file": "011_standalone_builders.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/standalone",
    "imagePath": "/designs/011_standalone_builders.png"
  },
  {
    "id": 12,
    "screenId": "DP-012",
    "originId": 7,
    "title": "Organization library",
    "group": "01 Start and navigate",
    "file": "012_resource_library.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/library",
    "imagePath": "/designs/012_resource_library.png"
  },
  {
    "id": 13,
    "screenId": "DP-013",
    "originId": 21,
    "title": "Application workspace",
    "group": "02 Compose and reuse",
    "file": "013_app_overview.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/apps/supplier-portal",
    "imagePath": "/designs/013_app_overview.png"
  },
  {
    "id": 14,
    "screenId": "DP-014",
    "originId": 22,
    "title": "Website workspace",
    "group": "02 Compose and reuse",
    "file": "014_site_overview.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/sites/supplier-website",
    "imagePath": "/designs/014_site_overview.png"
  },
  {
    "id": 15,
    "screenId": "DP-015",
    "originId": 9,
    "title": "Link library resource to project",
    "group": "02 Compose and reuse",
    "file": "015_link_to_project.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/supplier-experience/link-resource",
    "imagePath": "/designs/015_link_to_project.png"
  },
  {
    "id": 16,
    "screenId": "DP-016",
    "originId": 72,
    "title": "Link confirmation and dependency updates",
    "group": "02 Compose and reuse",
    "file": "016_resource_updates.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/supplier-experience/resource-updates",
    "imagePath": "/designs/016_resource_updates.png"
  },
  {
    "id": 17,
    "screenId": "DP-017",
    "originId": 93,
    "title": "Project export and import dry run",
    "group": "02 Compose and reuse",
    "file": "017_portable_import_export.png",
    "kind": "Enterprise addition",
    "gap": "Portability",
    "canonicalRoute": "/projects/supplier-experience/export-import",
    "imagePath": "/designs/017_portable_import_export.png"
  },
  {
    "id": 18,
    "screenId": "DP-018",
    "originId": 94,
    "title": "Library package release and overlays",
    "group": "02 Compose and reuse",
    "file": "018_package_publish_refined.png",
    "kind": "Enterprise addition",
    "gap": "Package publication",
    "canonicalRoute": "/library/packages/publish",
    "imagePath": "/designs/018_package_publish_refined.png"
  },
  {
    "id": 19,
    "screenId": "DP-019",
    "originId": 104,
    "title": "Package retirement and uninstall review",
    "group": "02 Compose and reuse",
    "file": "019_package_retirement_final.png",
    "kind": "Enterprise addition",
    "gap": "Dependency retirement",
    "canonicalRoute": "/library/packages/retirement",
    "imagePath": "/designs/019_package_retirement_final.png"
  },
  {
    "id": 20,
    "screenId": "DP-020",
    "originId": 8,
    "title": "Reusable component builder",
    "group": "02 Compose and reuse",
    "file": "020_component_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/components/new",
    "imagePath": "/designs/020_component_builder.png"
  },
  {
    "id": 21,
    "screenId": "DP-021",
    "originId": 56,
    "title": "Component lifecycle management",
    "group": "02 Compose and reuse",
    "file": "021_component_governance.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/manage/component-governance",
    "imagePath": "/designs/021_component_governance.png"
  },
  {
    "id": 22,
    "screenId": "DP-022",
    "originId": 75,
    "title": "Project lifecycle and general settings",
    "group": "02 Compose and reuse",
    "file": "022_project_settings.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/supplier-experience/settings",
    "imagePath": "/designs/022_project_settings.png"
  },
  {
    "id": 23,
    "screenId": "DP-023",
    "originId": 14,
    "title": "Project settings and access",
    "group": "02 Compose and reuse",
    "file": "023_project_settings.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/projects/supplier-experience/access",
    "imagePath": "/designs/023_project_settings.png"
  },
  {
    "id": 24,
    "screenId": "DP-024",
    "originId": 76,
    "title": "Developer command center and utilities",
    "group": "02 Compose and reuse",
    "file": "024_workspace_utilities.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/workspace/utilities",
    "imagePath": "/designs/024_workspace_utilities.png"
  },
  {
    "id": 25,
    "screenId": "DP-025",
    "originId": 16,
    "title": "Navigation and recovery states",
    "group": "02 Compose and reuse",
    "file": "025_navigation_states.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/system/navigation-states",
    "imagePath": "/designs/025_navigation_states.png"
  },
  {
    "id": 26,
    "screenId": "DP-026",
    "originId": 74,
    "title": "Loading empty error and access states",
    "group": "02 Compose and reuse",
    "file": "026_system_states.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/system/states",
    "imagePath": "/designs/026_system_states.png"
  },
  {
    "id": 27,
    "screenId": "DP-027",
    "originId": 23,
    "title": "Page tree and page creation",
    "group": "03 Build websites",
    "file": "027_pages.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/pages",
    "imagePath": "/designs/027_pages.png"
  },
  {
    "id": 28,
    "screenId": "DP-028",
    "originId": 4,
    "title": "Website visual builder",
    "group": "03 Build websites",
    "file": "028_website_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/canvas",
    "imagePath": "/designs/028_website_builder.png"
  },
  {
    "id": 29,
    "screenId": "DP-029",
    "originId": 24,
    "title": "CMS collections and records",
    "group": "03 Build websites",
    "file": "029_collections.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/collections",
    "imagePath": "/designs/029_collections.png"
  },
  {
    "id": 30,
    "screenId": "DP-030",
    "originId": 25,
    "title": "Collection schema and item editor",
    "group": "03 Build websites",
    "file": "030_collection_editor.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/collections/editor",
    "imagePath": "/designs/030_collection_editor.png"
  },
  {
    "id": 31,
    "screenId": "DP-031",
    "originId": 26,
    "title": "Blog publishing workspace",
    "group": "03 Build websites",
    "file": "031_blog.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/blog",
    "imagePath": "/designs/031_blog.png"
  },
  {
    "id": 32,
    "screenId": "DP-032",
    "originId": 27,
    "title": "Blog post editor",
    "group": "03 Build websites",
    "file": "032_post_editor.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/blog/editor",
    "imagePath": "/designs/032_post_editor.png"
  },
  {
    "id": 33,
    "screenId": "DP-033",
    "originId": 28,
    "title": "Asset library and upload",
    "group": "03 Build websites",
    "file": "033_assets.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/assets",
    "imagePath": "/designs/033_assets.png"
  },
  {
    "id": 34,
    "screenId": "DP-034",
    "originId": 29,
    "title": "Navigation menu builder",
    "group": "03 Build websites",
    "file": "034_menus.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/menus",
    "imagePath": "/designs/034_menus.png"
  },
  {
    "id": 35,
    "screenId": "DP-035",
    "originId": 30,
    "title": "SEO metadata and redirects",
    "group": "03 Build websites",
    "file": "035_seo.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/seo",
    "imagePath": "/designs/035_seo.png"
  },
  {
    "id": 36,
    "screenId": "DP-036",
    "originId": 95,
    "title": "Localization and RTL workbench",
    "group": "03 Build websites",
    "file": "036_localization_rtl_refined.png",
    "kind": "Enterprise addition",
    "gap": "Localization",
    "canonicalRoute": "/builder/web/localization",
    "imagePath": "/designs/036_localization_rtl_refined.png"
  },
  {
    "id": 37,
    "screenId": "DP-037",
    "originId": 96,
    "title": "Public access and consent",
    "group": "03 Build websites",
    "file": "037_public_access_consent_final.png",
    "kind": "Enterprise addition",
    "gap": "Website consent and public policy",
    "canonicalRoute": "/builder/web/consent",
    "imagePath": "/designs/037_public_access_consent_final.png"
  },
  {
    "id": 38,
    "screenId": "DP-038",
    "originId": 31,
    "title": "A/B experiment design",
    "group": "03 Build websites",
    "file": "038_experiments.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/experiments",
    "imagePath": "/designs/038_experiments.png"
  },
  {
    "id": 39,
    "screenId": "DP-039",
    "originId": 32,
    "title": "Website commerce orders",
    "group": "03 Build websites",
    "file": "039_orders.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/orders",
    "imagePath": "/designs/039_orders.png"
  },
  {
    "id": 40,
    "screenId": "DP-040",
    "originId": 33,
    "title": "Form submissions inbox",
    "group": "03 Build websites",
    "file": "040_submissions.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/submissions",
    "imagePath": "/designs/040_submissions.png"
  },
  {
    "id": 41,
    "screenId": "DP-041",
    "originId": 34,
    "title": "Site settings and domains",
    "group": "03 Build websites",
    "file": "041_site_settings.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/settings",
    "imagePath": "/designs/041_site_settings.png"
  },
  {
    "id": 42,
    "screenId": "DP-042",
    "originId": 35,
    "title": "Site revisions and rollback",
    "group": "03 Build websites",
    "file": "042_site_revisions.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/web/revisions",
    "imagePath": "/designs/042_site_revisions.png"
  },
  {
    "id": 43,
    "screenId": "DP-043",
    "originId": 5,
    "title": "Application visual builder",
    "group": "04 Build applications",
    "file": "043_app_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/app-builder",
    "imagePath": "/designs/043_app_builder.png"
  },
  {
    "id": 44,
    "screenId": "DP-044",
    "originId": 36,
    "title": "Forms catalog",
    "group": "04 Build applications",
    "file": "044_forms.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/forms",
    "imagePath": "/designs/044_forms.png"
  },
  {
    "id": 45,
    "screenId": "DP-045",
    "originId": 37,
    "title": "Form visual builder",
    "group": "04 Build applications",
    "file": "045_form_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/forms/builder",
    "imagePath": "/designs/045_form_builder.png"
  },
  {
    "id": 46,
    "screenId": "DP-046",
    "originId": 38,
    "title": "Advanced forms and field library",
    "group": "04 Build applications",
    "file": "046_advanced_forms.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/advanced-forms",
    "imagePath": "/designs/046_advanced_forms.png"
  },
  {
    "id": 47,
    "screenId": "DP-047",
    "originId": 40,
    "title": "Dashboard catalog and creation",
    "group": "04 Build applications",
    "file": "047_dashboard_catalog.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/dashboards",
    "imagePath": "/designs/047_dashboard_catalog.png"
  },
  {
    "id": 48,
    "screenId": "DP-048",
    "originId": 41,
    "title": "Dashboard visual builder",
    "group": "04 Build applications",
    "file": "048_dashboard_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/dashboards/builder",
    "imagePath": "/designs/048_dashboard_builder.png"
  },
  {
    "id": 49,
    "screenId": "DP-049",
    "originId": 42,
    "title": "Data objects catalog",
    "group": "04 Build applications",
    "file": "049_data_objects.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/data-objects",
    "imagePath": "/designs/049_data_objects.png"
  },
  {
    "id": 50,
    "screenId": "DP-050",
    "originId": 43,
    "title": "Object schema and relationships",
    "group": "04 Build applications",
    "file": "050_object_designer.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/data-objects/designer",
    "imagePath": "/designs/050_object_designer.png"
  },
  {
    "id": 51,
    "screenId": "DP-051",
    "originId": 45,
    "title": "Decision table and rule designer",
    "group": "04 Build applications",
    "file": "051_rules.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/rules-engine",
    "imagePath": "/designs/051_rules.png"
  },
  {
    "id": 52,
    "screenId": "DP-052",
    "originId": 44,
    "title": "BPMN process designer",
    "group": "04 Build applications",
    "file": "052_bpmn.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/bpmn",
    "imagePath": "/designs/052_bpmn.png"
  },
  {
    "id": 53,
    "screenId": "DP-053",
    "originId": 39,
    "title": "Workflow catalog and creation",
    "group": "04 Build applications",
    "file": "053_workflow_catalog.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/workflows",
    "imagePath": "/designs/053_workflow_catalog.png"
  },
  {
    "id": 54,
    "screenId": "DP-054",
    "originId": 11,
    "title": "Workflow and interaction builder",
    "group": "04 Build applications",
    "file": "054_workflow_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/workflows/builder",
    "imagePath": "/designs/054_workflow_builder.png"
  },
  {
    "id": 55,
    "screenId": "DP-055",
    "originId": 47,
    "title": "Logic script workbench",
    "group": "04 Build applications",
    "file": "055_logic.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/logic",
    "imagePath": "/designs/055_logic.png"
  },
  {
    "id": 56,
    "screenId": "DP-056",
    "originId": 48,
    "title": "Mobile app visual builder",
    "group": "04 Build applications",
    "file": "056_mobile_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/mobile-builder",
    "imagePath": "/designs/056_mobile_builder.png"
  },
  {
    "id": 57,
    "screenId": "DP-057",
    "originId": 49,
    "title": "Application navigation customization",
    "group": "04 Build applications",
    "file": "057_app_customization.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/customize",
    "imagePath": "/designs/057_app_customization.png"
  },
  {
    "id": 58,
    "screenId": "DP-058",
    "originId": 105,
    "title": "Report and metric designer",
    "group": "04 Build applications",
    "file": "058_report_semantics.png",
    "kind": "Enterprise addition",
    "gap": "Governed reporting",
    "canonicalRoute": "/builder/erp/reports",
    "imagePath": "/designs/058_report_semantics.png"
  },
  {
    "id": 59,
    "screenId": "DP-059",
    "originId": 106,
    "title": "Notification and document templates",
    "group": "04 Build applications",
    "file": "059_message_templates.png",
    "kind": "Enterprise addition",
    "gap": "Reusable template design",
    "canonicalRoute": "/builder/erp/templates",
    "imagePath": "/designs/059_message_templates.png"
  },
  {
    "id": 60,
    "screenId": "DP-060",
    "originId": 107,
    "title": "Approval routing and delegation",
    "group": "04 Build applications",
    "file": "060_approval_routing.png",
    "kind": "Enterprise addition",
    "gap": "Approval policy design",
    "canonicalRoute": "/builder/erp/approval-routing",
    "imagePath": "/designs/060_approval_routing.png"
  },
  {
    "id": 61,
    "screenId": "DP-061",
    "originId": 10,
    "title": "Data and integrations",
    "group": "05 Integrate and extend",
    "file": "061_data_integrations.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/integrations",
    "imagePath": "/designs/061_data_integrations.png"
  },
  {
    "id": 62,
    "screenId": "DP-062",
    "originId": 57,
    "title": "Connectors catalog and configuration",
    "group": "05 Integrate and extend",
    "file": "062_connectors.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/connectors",
    "imagePath": "/designs/062_connectors.png"
  },
  {
    "id": 63,
    "screenId": "DP-063",
    "originId": 59,
    "title": "Visual query builder",
    "group": "05 Integrate and extend",
    "file": "063_query_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/query-builder",
    "imagePath": "/designs/063_query_builder.png"
  },
  {
    "id": 64,
    "screenId": "DP-064",
    "originId": 60,
    "title": "Reusable widget builder",
    "group": "05 Integrate and extend",
    "file": "064_widgets.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/widgets",
    "imagePath": "/designs/064_widgets.png"
  },
  {
    "id": 65,
    "screenId": "DP-065",
    "originId": 61,
    "title": "ETL pipeline designer",
    "group": "05 Integrate and extend",
    "file": "065_etl.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/etl",
    "imagePath": "/designs/065_etl.png"
  },
  {
    "id": 66,
    "screenId": "DP-066",
    "originId": 46,
    "title": "Custom API designer",
    "group": "05 Integrate and extend",
    "file": "066_api_builder.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/erp/api-builder",
    "imagePath": "/designs/066_api_builder.png"
  },
  {
    "id": 67,
    "screenId": "DP-067",
    "originId": 15,
    "title": "API and extensions",
    "group": "05 Integrate and extend",
    "file": "067_api_extensions.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/api-extensions",
    "imagePath": "/designs/067_api_extensions.png"
  },
  {
    "id": 68,
    "screenId": "DP-068",
    "originId": 65,
    "title": "SDK documentation and quickstart",
    "group": "05 Integrate and extend",
    "file": "068_sdk.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/sdk",
    "imagePath": "/designs/068_sdk.png"
  },
  {
    "id": 69,
    "screenId": "DP-069",
    "originId": 108,
    "title": "API contract publication and consumers",
    "group": "05 Integrate and extend",
    "file": "069_contract_publication_refined.png",
    "kind": "Enterprise addition",
    "gap": "Contract compatibility",
    "canonicalRoute": "/contracts/publication",
    "imagePath": "/designs/069_contract_publication_refined.png"
  },
  {
    "id": 70,
    "screenId": "DP-070",
    "originId": 68,
    "title": "Extensions catalog",
    "group": "05 Integrate and extend",
    "file": "070_extensions.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/extensions",
    "imagePath": "/designs/070_extensions.png"
  },
  {
    "id": 71,
    "screenId": "DP-071",
    "originId": 69,
    "title": "Extension bundle validation",
    "group": "05 Integrate and extend",
    "file": "071_extension_package.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/extensions/validation",
    "imagePath": "/designs/071_extension_package.png"
  },
  {
    "id": 72,
    "screenId": "DP-072",
    "originId": 70,
    "title": "Sandbox execution console",
    "group": "05 Integrate and extend",
    "file": "072_sandbox.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/sandbox",
    "imagePath": "/designs/072_sandbox.png"
  },
  {
    "id": 73,
    "screenId": "DP-073",
    "originId": 71,
    "title": "API diagnostics quotas and deprecations",
    "group": "05 Integrate and extend",
    "file": "073_diagnostics.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/api/diagnostics",
    "imagePath": "/designs/073_diagnostics.png"
  },
  {
    "id": 74,
    "screenId": "DP-074",
    "originId": 85,
    "title": "Events webhooks and redelivery",
    "group": "05 Integrate and extend",
    "file": "074_webhook_events.png",
    "kind": "Enterprise addition",
    "gap": "Event delivery",
    "canonicalRoute": "/events/webhooks",
    "imagePath": "/designs/074_webhook_events.png"
  },
  {
    "id": 75,
    "screenId": "DP-075",
    "originId": 86,
    "title": "Schedules jobs and compensation",
    "group": "05 Integrate and extend",
    "file": "075_jobs_schedules.png",
    "kind": "Enterprise addition",
    "gap": "Durable job operations",
    "canonicalRoute": "/schedules/jobs",
    "imagePath": "/designs/075_jobs_schedules.png"
  },
  {
    "id": 76,
    "screenId": "DP-076",
    "originId": 12,
    "title": "Preview and quality",
    "group": "06 Validate and deliver",
    "file": "076_responsive_preview.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/preview/quality",
    "imagePath": "/designs/076_responsive_preview.png"
  },
  {
    "id": 77,
    "screenId": "DP-077",
    "originId": 81,
    "title": "Test suite designer",
    "group": "06 Validate and deliver",
    "file": "077_test_suite_builder.png",
    "kind": "Enterprise addition",
    "gap": "Test authoring",
    "canonicalRoute": "/tests/builder",
    "imagePath": "/designs/077_test_suite_builder.png"
  },
  {
    "id": 78,
    "screenId": "DP-078",
    "originId": 82,
    "title": "Test run evidence",
    "group": "06 Validate and deliver",
    "file": "078_test_evidence_refined.png",
    "kind": "Enterprise addition",
    "gap": "Quality evidence",
    "canonicalRoute": "/tests/evidence",
    "imagePath": "/designs/078_test_evidence_refined.png"
  },
  {
    "id": 79,
    "screenId": "DP-079",
    "originId": 79,
    "title": "Changeset and dependency impact",
    "group": "06 Validate and deliver",
    "file": "079_change_impact.png",
    "kind": "Enterprise addition",
    "gap": "Semantic change review",
    "canonicalRoute": "/changesets/impact",
    "imagePath": "/designs/079_change_impact.png"
  },
  {
    "id": 80,
    "screenId": "DP-080",
    "originId": 80,
    "title": "Collaborative review and conflicts",
    "group": "06 Validate and deliver",
    "file": "080_collaboration_review_refined.png",
    "kind": "Enterprise addition",
    "gap": "Concurrent editing",
    "canonicalRoute": "/collaboration/review",
    "imagePath": "/designs/080_collaboration_review_refined.png"
  },
  {
    "id": 81,
    "screenId": "DP-081",
    "originId": 63,
    "title": "Source control and merge review",
    "group": "06 Validate and deliver",
    "file": "081_git.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/git",
    "imagePath": "/designs/081_git.png"
  },
  {
    "id": 82,
    "screenId": "DP-082",
    "originId": 99,
    "title": "Metadata migration and reconciliation",
    "group": "06 Validate and deliver",
    "file": "082_schema_migration.png",
    "kind": "Enterprise addition",
    "gap": "Schema migration",
    "canonicalRoute": "/database/migrations",
    "imagePath": "/designs/082_schema_migration.png"
  },
  {
    "id": 83,
    "screenId": "DP-083",
    "originId": 62,
    "title": "Theme and token editor",
    "group": "06 Validate and deliver",
    "file": "083_theme_manager.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/theme-manager",
    "imagePath": "/designs/083_theme_manager.png"
  },
  {
    "id": 84,
    "screenId": "DP-084",
    "originId": 100,
    "title": "Builder registration and conformance",
    "group": "06 Validate and deliver",
    "file": "084_builder_conformance_refined.png",
    "kind": "Enterprise addition",
    "gap": "Builder plugin governance",
    "canonicalRoute": "/conformance/builder",
    "imagePath": "/designs/084_builder_conformance_refined.png"
  },
  {
    "id": 85,
    "screenId": "DP-085",
    "originId": 13,
    "title": "Release review",
    "group": "06 Validate and deliver",
    "file": "085_releases.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/releases",
    "imagePath": "/designs/085_releases.png"
  },
  {
    "id": 86,
    "screenId": "DP-086",
    "originId": 52,
    "title": "Cross-project release history",
    "group": "06 Validate and deliver",
    "file": "086_release_history.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/releases/history",
    "imagePath": "/designs/086_release_history.png"
  },
  {
    "id": 87,
    "screenId": "DP-087",
    "originId": 53,
    "title": "Environments and configuration",
    "group": "06 Validate and deliver",
    "file": "087_environments.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/environments",
    "imagePath": "/designs/087_environments.png"
  },
  {
    "id": 88,
    "screenId": "DP-088",
    "originId": 103,
    "title": "Environment provisioning and synthetic data",
    "group": "06 Validate and deliver",
    "file": "088_environment_bootstrap_final.png",
    "kind": "Enterprise addition",
    "gap": "Environment readiness",
    "canonicalRoute": "/environments/bootstrap",
    "imagePath": "/designs/088_environment_bootstrap_final.png"
  },
  {
    "id": 89,
    "screenId": "DP-089",
    "originId": 83,
    "title": "Release pipeline and approval",
    "group": "06 Validate and deliver",
    "file": "089_release_pipeline_refined.png",
    "kind": "Enterprise addition",
    "gap": "Promotion approvals",
    "canonicalRoute": "/releases/pipeline",
    "imagePath": "/designs/089_release_pipeline_refined.png"
  },
  {
    "id": 90,
    "screenId": "DP-090",
    "originId": 84,
    "title": "Deployment failure and recovery",
    "group": "06 Validate and deliver",
    "file": "090_deployment_recovery_refined.png",
    "kind": "Enterprise addition",
    "gap": "Deployment recovery",
    "canonicalRoute": "/deployments/recovery",
    "imagePath": "/designs/090_deployment_recovery_refined.png"
  },
  {
    "id": 91,
    "screenId": "DP-091",
    "originId": 64,
    "title": "Mobile packaging and export",
    "group": "06 Validate and deliver",
    "file": "091_mobile_export.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/mobile-export",
    "imagePath": "/designs/091_mobile_export.png"
  },
  {
    "id": 92,
    "screenId": "DP-092",
    "originId": 50,
    "title": "Manage workspace",
    "group": "07 Secure and operate",
    "file": "092_manage.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/manage",
    "imagePath": "/designs/092_manage.png"
  },
  {
    "id": 93,
    "screenId": "DP-093",
    "originId": 51,
    "title": "Developer governance and capacity",
    "group": "07 Secure and operate",
    "file": "093_governance.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/developer-governance",
    "imagePath": "/designs/093_governance.png"
  },
  {
    "id": 94,
    "screenId": "DP-094",
    "originId": 55,
    "title": "Developer access control",
    "group": "07 Secure and operate",
    "file": "094_access_control.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/access",
    "imagePath": "/designs/094_access_control.png"
  },
  {
    "id": 95,
    "screenId": "DP-095",
    "originId": 66,
    "title": "Application credentials inventory",
    "group": "07 Secure and operate",
    "file": "095_credentials.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/credentials",
    "imagePath": "/designs/095_credentials.png"
  },
  {
    "id": 96,
    "screenId": "DP-096",
    "originId": 67,
    "title": "Create and rotate credentials",
    "group": "07 Secure and operate",
    "file": "096_credential_lifecycle.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/credentials/lifecycle",
    "imagePath": "/designs/096_credential_lifecycle.png"
  },
  {
    "id": 97,
    "screenId": "DP-097",
    "originId": 87,
    "title": "Record and field policy simulator",
    "group": "07 Secure and operate",
    "file": "097_record_field_policy.png",
    "kind": "Enterprise addition",
    "gap": "Granular authorization",
    "canonicalRoute": "/policies/simulator",
    "imagePath": "/designs/097_record_field_policy.png"
  },
  {
    "id": 98,
    "screenId": "DP-098",
    "originId": 88,
    "title": "Environment secret bindings",
    "group": "07 Secure and operate",
    "file": "098_secret_bindings.png",
    "kind": "Enterprise addition",
    "gap": "Secret reference lifecycle",
    "canonicalRoute": "/secrets/bindings",
    "imagePath": "/designs/098_secret_bindings.png"
  },
  {
    "id": 99,
    "screenId": "DP-099",
    "originId": 89,
    "title": "Supply chain and security review",
    "group": "07 Secure and operate",
    "file": "099_supply_chain_review_refined.png",
    "kind": "Enterprise addition",
    "gap": "Package security",
    "canonicalRoute": "/security/supply-chain",
    "imagePath": "/designs/099_supply_chain_review_refined.png"
  },
  {
    "id": 100,
    "screenId": "DP-100",
    "originId": 90,
    "title": "Extension quarantine and revocation",
    "group": "07 Secure and operate",
    "file": "100_extension_quarantine.png",
    "kind": "Enterprise addition",
    "gap": "Extension containment",
    "canonicalRoute": "/security/quarantine",
    "imagePath": "/designs/100_extension_quarantine.png"
  },
  {
    "id": 101,
    "screenId": "DP-101",
    "originId": 91,
    "title": "Audit trail and evidence export",
    "group": "07 Secure and operate",
    "file": "101_audit_evidence.png",
    "kind": "Enterprise addition",
    "gap": "Audit accountability",
    "canonicalRoute": "/audit/evidence",
    "imagePath": "/designs/101_audit_evidence.png"
  },
  {
    "id": 102,
    "screenId": "DP-102",
    "originId": 92,
    "title": "Restore rehearsal and recovery",
    "group": "07 Secure and operate",
    "file": "102_backup_restore_refined.png",
    "kind": "Enterprise addition",
    "gap": "Disaster recovery",
    "canonicalRoute": "/backup/restore",
    "imagePath": "/designs/102_backup_restore_refined.png"
  },
  {
    "id": 103,
    "screenId": "DP-103",
    "originId": 97,
    "title": "Application health and incidents",
    "group": "07 Secure and operate",
    "file": "103_service_health_refined.png",
    "kind": "Enterprise addition",
    "gap": "SLO and incident response",
    "canonicalRoute": "/service/health",
    "imagePath": "/designs/103_service_health_refined.png"
  },
  {
    "id": 104,
    "screenId": "DP-104",
    "originId": 98,
    "title": "Usage budgets and entitlement limits",
    "group": "07 Secure and operate",
    "file": "104_usage_budgets.png",
    "kind": "Enterprise addition",
    "gap": "Capacity budgets",
    "canonicalRoute": "/usage/budgets",
    "imagePath": "/designs/104_usage_budgets.png"
  },
  {
    "id": 105,
    "screenId": "DP-105",
    "originId": 102,
    "title": "Application identity and session policies",
    "group": "07 Secure and operate",
    "file": "105_app_identity.png",
    "kind": "Enterprise addition",
    "gap": "Runtime identity configuration",
    "canonicalRoute": "/identity/policies",
    "imagePath": "/designs/105_app_identity.png"
  },
  {
    "id": 106,
    "screenId": "DP-106",
    "originId": 101,
    "title": "AI-assisted change review",
    "group": "07 Secure and operate",
    "file": "106_ai_assisted_changes.png",
    "kind": "Enterprise addition",
    "gap": "AI governance",
    "canonicalRoute": "/ai/change-review",
    "imagePath": "/designs/106_ai_assisted_changes.png"
  },
  {
    "id": 107,
    "screenId": "DP-107",
    "originId": 54,
    "title": "Run logs and trace detail",
    "group": "07 Secure and operate",
    "file": "107_run_logs.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/logs",
    "imagePath": "/designs/107_run_logs.png"
  },
  {
    "id": 108,
    "screenId": "DP-108",
    "originId": 58,
    "title": "Marketplace packages and installation review",
    "group": "07 Secure and operate",
    "file": "108_marketplace_packages.png",
    "kind": "Consolidated",
    "gap": null,
    "canonicalRoute": "/builder/manage/marketplace",
    "imagePath": "/designs/108_marketplace_packages.png"
  }
];

export function getScreenById(screenId: string): ScreenDescriptor | undefined {
  return ALL_SCREENS.find(
    (s) => s.screenId.toLowerCase() === screenId.toLowerCase() || `DP-${s.id}`.toLowerCase() === screenId.toLowerCase()
  );
}

export function getScreensByGroup(group: string): ScreenDescriptor[] {
  return ALL_SCREENS.filter((s) => s.group === group);
}
